### ISSUE TITLE
Setup Development Environment

### ISSUE THREAD

**Issue by heobu** [8hk/AEK#24]
It is necessary to create a development environment for the project.

To that end, it is important to investigate what will be required and to apply them for your development environment, along with standardizing and documenting the process as much as possible.

This also includes investigating what would be the best option for a database in order to store annotations, and setting that up for the development environment as well.

**Comment by heobu** [comment]
We can start by using Django in our own environment but the consensus is that we should dockerize our solution going forward.

**Comment by 8hk** [comment]
We decided to create a docker image instead of setup the env for each team member.  
Because we will use Django+ MongoDB+ Elasticsearch stack for this project. Setup this stack for each team member requires lots of efforts but creating docker compose file decreases the work load. It is also more useful while setup prod and CI env also.  So we are closing this issue.
